
import Link from "next/link";
import ComponentsPage from "./_components/page";

export const metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <div>

      <ComponentsPage />

      <h1 className="text-3xl font-bold underline">Hello world! 2</h1>
      <p><Link href="/about">About</Link></p>
      <p><Link href="/services">Services</Link></p>
      <p><Link href="/blogs">Blogs</Link></p>
    </div>
  );
}
