export const metadata = {
  title: "About Page",
  description: "Generated by Next.js",
};


const About =()=> {   
  return (
    <div>
      <h1 className="text-3xl font-bold underline">About Us</h1>
      <p>Welcome to our about page!</p>
    </div>
  );
}
export default About
