export default [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    phone: '9876543210',
    age: 28,
    city: 'Pune',
    country: 'India',
    isActive: true,
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '8765432109',
    age: 25,
    city: 'Mumbai',
    country: 'India',
    isActive: false,
  },
  {
    id: 3,
    name: 'Michael Johnson',
    email: 'michael@example.com',
    phone: '7654321098',
    age: 32,
    city: 'Delhi',
    country: 'India',
    isActive: true,
  },
  {
    id: 4,
    name: 'Emily Brown',
    email: 'emily@example.com',
    phone: '6543210987',
    age: 29,
    city: 'Bengaluru',
    country: 'India',
    isActive: true,
  },
  {
    id: 5,
    name: 'David Wilson',
    email: 'david@example.com',
    phone: '5432109876',
    age: 35,
    city: 'Hyderabad',
    country: 'India',
    isActive: false,
  },
];
